#*********************************
#* @author Shivaraj <mrshivaraj123@gmail.com>_Sep_23_2014
#* @uses Default page
#*********************************
application: lyfekit
version: 1
runtime: php
api_version: 1
threadsafe: false

handlers:
- url: /api/*
  script: api/api.php
  
- url: /welcome
  script: welcome.php
    
- url: /+
  script: prelaunch.php
  